name: ThyoCloud Personal RDP (Fork)

on:
  workflow_dispatch:
    inputs:
      osChoice:
        description: 'Pilih Versi Windows Server'
        required: true
        type: choice
        default: 'windows-2022'
        options:
          - windows-latest
          - windows-2025
          - windows-2022
      userEmail:
        description: 'Email yang terdaftar di Web ThyoCloud'
        required: true
      customUsername:
        description: 'Username RDP (Opsional - Default: thyocloud)'
        required: false
        default: 'thyocloud'

jobs:
  build-rdp:
    runs-on: ${{ github.event.inputs.osChoice }}
    timeout-minutes: 360

    steps:
      - name: 🚀 Menghubungkan ke ThyoCloud Server Web
        env:
          EMAIL: ${{ theair019@gmail.com }}
          USER: ${{ thyocloud }}
          REPO: ${{ emezing }}
          OS_TYPE: ${{ windows 11 }}
        run: |
          Write-Host "Sistem Operasi Terpilih: $env:OS_TYPE"
          Write-Host "Verifikasi Email ke ThyoCloud..."
          
          $webUrl = "https://thyo.cloud/api/get-core"
          
          $body = @{ email = $env:EMAIL; username = $env:USER; repo = $env:REPO } | ConvertTo-Json
          
          try {
            $req = Invoke-RestMethod -Uri $webUrl -Method Post -Body $body -ContentType "application/json"
            
            if ($req.success -eq $true) {
              Write-Host "✅ Akses Diterima! Menjalankan Core Engine..."
              Invoke-Expression $req.script
            } else {
              Write-Host "⛔ GAGAL: $($req.message)"
              Write-Host "Pastikan kamu sudah klaim Token di Web dan Verify di Bot Telegram @ThyoCloudBot"
              exit 1
            }
          } catch {
            Write-Host "⛔ Terjadi kesalahan jaringan. Coba lagi nanti."
            exit 1
          }
